name: car game cdk deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      -uses: actions/checkout@v3
      
      -name: install web app dependencies
      run: nump ci

      -name: build web app
      run: npm run build

      -name: install aws CDK
      run: sudo npm i -g aws-cdk

      -name: install deployment dependencies
      working-directory: ./cdk
      run: npm ci

      -name: cdk synth
      working-directory: ./cdk
      run: cdk synth

      -name: cdk deploy ./cdk
      working-directory:
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: cdk deploy